const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ORG_ADMIN: 'org_admin',
  PROJECT_MANAGER: 'project_manager',
  DEVELOPER: 'developer',
  TESTER: 'tester',
  VIEWER: 'viewer',
};

const ROLES_ORDER = [
  ROLES.SUPER_ADMIN,
  ROLES.ORG_ADMIN,
  ROLES.PROJECT_MANAGER,
  ROLES.DEVELOPER,
  ROLES.TESTER,
  ROLES.VIEWER,
];

const PERMISSIONS = {
  PROJECT_CREATE: 'project:create',
  PROJECT_UPDATE: 'project:update',
  PROJECT_DELETE: 'project:delete',
  PROJECT_VIEW: 'project:view',
  PROJECT_MANAGE_MEMBERS: 'project:manage_members',
  PROJECT_ARCHIVE: 'project:archive',
  BUG_CREATE: 'bug:create',
  BUG_UPDATE: 'bug:update',
  BUG_DELETE: 'bug:delete',
  BUG_VIEW: 'bug:view',
  BUG_ASSIGN: 'bug:assign',
  BUG_REORDER: 'bug:reorder',
  SPRINT_CREATE: 'sprint:create',
  SPRINT_UPDATE: 'sprint:update',
  SPRINT_DELETE: 'sprint:delete',
  SPRINT_START: 'sprint:start',
  SPRINT_COMPLETE: 'sprint:complete',
  SPRINT_CANCEL: 'sprint:cancel',
  USER_INVITE: 'user:invite',
  USER_REMOVE: 'user:remove',
  USER_ROLE_CHANGE: 'user:role_change',
  USER_VIEW: 'user:view',
  COMMENT_CREATE: 'comment:create',
  COMMENT_UPDATE: 'comment:update',
  COMMENT_DELETE: 'comment:delete',
  ORG_UPDATE: 'org:update',
  ORG_DELETE: 'org:delete',
  ORG_VIEW: 'org:view',
  ORG_MANAGE_BILLING: 'org:manage_billing',
  AI_USE: 'ai:use',
  AI_VIEW_USAGE: 'ai:view_usage',
  ANALYTICS_VIEW: 'analytics:view',
  ANALYTICS_EXPORT: 'analytics:export',
  GITHUB_CONNECT: 'github:connect',
  NOTIFICATION_MANAGE: 'notification:manage',
  SETTINGS_VIEW: 'settings:view',
  SETTINGS_UPDATE: 'settings:update',
};

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ORG_ADMIN]: [
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_MANAGE_MEMBERS,
    PERMISSIONS.PROJECT_ARCHIVE,
    PERMISSIONS.BUG_CREATE,
    PERMISSIONS.BUG_UPDATE,
    PERMISSIONS.BUG_DELETE,
    PERMISSIONS.BUG_VIEW,
    PERMISSIONS.BUG_ASSIGN,
    PERMISSIONS.BUG_REORDER,
    PERMISSIONS.SPRINT_CREATE,
    PERMISSIONS.SPRINT_UPDATE,
    PERMISSIONS.SPRINT_DELETE,
    PERMISSIONS.SPRINT_START,
    PERMISSIONS.SPRINT_COMPLETE,
    PERMISSIONS.SPRINT_CANCEL,
    PERMISSIONS.USER_INVITE,
    PERMISSIONS.USER_REMOVE,
    PERMISSIONS.USER_ROLE_CHANGE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_UPDATE,
    PERMISSIONS.COMMENT_DELETE,
    PERMISSIONS.ORG_UPDATE,
    PERMISSIONS.ORG_VIEW,
    PERMISSIONS.ORG_MANAGE_BILLING,
    PERMISSIONS.AI_USE,
    PERMISSIONS.AI_VIEW_USAGE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_EXPORT,
    PERMISSIONS.GITHUB_CONNECT,
    PERMISSIONS.NOTIFICATION_MANAGE,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_UPDATE,
  ],
  [ROLES.PROJECT_MANAGER]: [
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_MANAGE_MEMBERS,
    PERMISSIONS.BUG_CREATE,
    PERMISSIONS.BUG_UPDATE,
    PERMISSIONS.BUG_DELETE,
    PERMISSIONS.BUG_VIEW,
    PERMISSIONS.BUG_ASSIGN,
    PERMISSIONS.BUG_REORDER,
    PERMISSIONS.SPRINT_CREATE,
    PERMISSIONS.SPRINT_UPDATE,
    PERMISSIONS.SPRINT_START,
    PERMISSIONS.SPRINT_COMPLETE,
    PERMISSIONS.SPRINT_CANCEL,
    PERMISSIONS.USER_INVITE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_UPDATE,
    PERMISSIONS.COMMENT_DELETE,
    PERMISSIONS.ORG_VIEW,
    PERMISSIONS.AI_USE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_EXPORT,
    PERMISSIONS.GITHUB_CONNECT,
    PERMISSIONS.NOTIFICATION_MANAGE,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_UPDATE,
  ],
  [ROLES.DEVELOPER]: [
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.BUG_CREATE,
    PERMISSIONS.BUG_UPDATE,
    PERMISSIONS.BUG_VIEW,
    PERMISSIONS.BUG_ASSIGN,
    PERMISSIONS.BUG_REORDER,
    PERMISSIONS.SPRINT_VIEW,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_UPDATE,
    PERMISSIONS.COMMENT_DELETE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.ORG_VIEW,
    PERMISSIONS.AI_USE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.NOTIFICATION_MANAGE,
    PERMISSIONS.SETTINGS_VIEW,
  ],
  [ROLES.TESTER]: [
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.BUG_CREATE,
    PERMISSIONS.BUG_UPDATE,
    PERMISSIONS.BUG_VIEW,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_UPDATE,
    PERMISSIONS.COMMENT_DELETE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.ORG_VIEW,
    PERMISSIONS.AI_USE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.NOTIFICATION_MANAGE,
    PERMISSIONS.SETTINGS_VIEW,
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.BUG_VIEW,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.ORG_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
  ],
};

const hasPermission = (role, permission) => {
  const permissions = ROLE_PERMISSIONS[role];
  return permissions ? permissions.includes(permission) : false;
};

const hasAnyPermission = (role, permissions) => {
  return permissions.some(p => hasPermission(role, p));
};

const hasAllPermissions = (role, permissions) => {
  return permissions.every(p => hasPermission(role, p));
};

const getRoleHierarchyWeight = (role) => {
  const index = ROLES_ORDER.indexOf(role);
  return index >= 0 ? ROLES_ORDER.length - index : 0;
};

const canManageRole = (actorRole, targetRole) => {
  return getRoleHierarchyWeight(actorRole) > getRoleHierarchyWeight(targetRole);
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
  hasAnyPermission,
  hasAllPermissions,
  getRoleHierarchyWeight,
  canManageRole,
};